version: "3.9"

services:
  app:
    build: .
    command: sh -c "python main.py"
    volumes:
      - .:/app
    restart: no
    env_file:
      - .env
    networks:
      - postgres-network

  database:
    image: postgres:15-alpine3.18
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network: { }

volumes:
  postgres-data: { }